clearvars -except AMPLITUDE Ang3D AngHeadTail3D AnimalAnalyzed ...
    BASELINE_PER_EPISODE baseline_swimming_gen bottombaseline Coor3D...
    DistanceHead EPISODE_BASELINE_AMP_SIGN EPISODE_X EPISODE_Y ...
    EPISODE_Y_BASELINE_AMP EPISODE_Y_BASELINE_AMP_AVGR EPISODE_Y_BASELINE_AMP_AVGR_NORM...
    EPISODE_Y_BASELINE_AMP_NORM EPISODE_Y_BASELINE_AMP_SIGN Final_points_swimming...
    frames FREQ laserframe laserframeOFF laserframeON LengthAnimal LengthAnimalStd...
    LengthAnimalFrames locs1 locs2 Name pks1 pks2 SC1 SC2 SC3 SC4 SC5 SC6 SC7 SC8 ...
    sidepeaks sidetroughts sign_retention std_baseline std_baseline_gen std_used...
    SumAng3D SumAng3DPosi Vec3D path CurrentSavingPath SelectedaCell CYCLES_AFTER_C PeaksAfterC...
    FrameC AmplitudeC Latency TypeExperiment CandidateCAmplitude CandidateCFrame AmplitudePeaksAfterC...
    wave